# Generated by Django 4.0.2 on 2022-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
