# Generated by Django 4.0.2 on 2022-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='product',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
