# Generated by Django 4.0.2 on 2022-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prices',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
