# Generated by Django 4.0.2 on 2022-04-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_wish_price_task_wishprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prices',
            new_name='old_price',
        ),
    ]
